"""MCP surface for the project-workspace v2 plugin.

Registers a ``startup`` callback that loads ``.code_puppy/mcp_servers.json``
from the workspace root and injects the project MCP servers into the
MCPManager singleton registry.

Scope semantics
---------------
merge   — global servers (already loaded by MCPManager.sync_from_config())
          remain active.  Project servers from ``.code_puppy/mcp_servers.json``
          are injected on top.  When a project server has the same name as a
          global server, the **project config wins** (the global entry is
          updated in-place).

project — Same injection as ``merge``.  Additionally, any global server that
          is NOT overridden by a project server is disabled via
          ``ManagedMCPServer.disable()``.  Falls through to global behaviour
          (no disable, no inject) when there is no workspace root or the
          workspace has no ``mcp_servers.json``.

global  — Noop.  Project servers are not injected.

Core edit note
--------------
None.  This surface uses the MCPManager's existing public API:

- ``manager.registry.list_all()`` — snapshot current global servers
- ``manager.registry.get_by_name(name)`` — collision check
- ``manager.register_server(config)`` — add new server + ManagedMCPServer
- ``manager.update_server(server_id, config)`` — project-wins update
- ``manager.get_server(server_id).disable()`` — disable a global server

**Persistence note**: project servers added via ``register_server()`` are
written to ``mcp_registry.json`` (XDG_DATA_HOME).  They will persist across
sessions until explicitly removed.  A future cleanup phase could unregister
project servers on ``shutdown`` when the workspace context has changed.

See docs/workspace-plugin-design.md § Surface Integration Plan → 4. MCP
Surface and beads ticket code_puppy-z1q.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _load_mcp_servers_from_file(file_path: Path) -> dict[str, dict]:
    """Parse an ``mcp_servers.json`` file and return ``{name: raw_config_dict}``.

    The expected structure mirrors the global ``mcp_servers.json``::

        {
            "mcp_servers": {
                "my-server": { "type": "stdio", "command": "uvx", ... }
            }
        }

    Returns an empty dict when the file does not exist, cannot be read, or
    has unexpected structure.  Never raises.
    """
    if not file_path.exists():
        return {}
    try:
        data = json.loads(file_path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        logger.warning(
            "[project_workspace/mcp] malformed JSON in %s: %s — skipping",
            file_path,
            exc,
        )
        return {}
    except Exception as exc:
        logger.warning(
            "[project_workspace/mcp] could not read %s: %s — skipping",
            file_path,
            exc,
        )
        return {}

    servers = data.get("mcp_servers", {})
    if not isinstance(servers, dict):
        logger.warning(
            "[project_workspace/mcp] %s: 'mcp_servers' must be a dict — skipping",
            file_path,
        )
        return {}
    return servers


def _make_server_config(name: str, raw_config: dict) -> Any | None:
    """Build a ``ServerConfig`` from a raw config dict.

    Returns ``None`` and logs a warning if the import or construction fails.
    """
    try:
        from code_puppy.mcp_.managed_server import ServerConfig

        return ServerConfig(
            id=raw_config.get("id", ""),  # Empty ID → auto-generated by registry
            name=name,
            type=raw_config.get("type", "sse"),
            enabled=raw_config.get("enabled", True),
            config=raw_config,
        )
    except Exception as exc:
        logger.warning(
            "[project_workspace/mcp] could not build ServerConfig for %r: %s",
            name,
            exc,
        )
        return None


def _inject_servers(
    project_servers: dict[str, dict],
    manager: Any,
    existing_by_name: dict[str, Any],
) -> None:
    """Register or update project servers in the manager registry.

    For each project server:
    - If no global server with that name exists: call ``register_server()``.
    - If a global server with that name exists: call ``update_server()``
      (project config wins).

    Errors per-server are logged and skipped; other servers continue.
    """
    for name, raw_config in project_servers.items():
        config = _make_server_config(name, raw_config)
        if config is None:
            continue

        existing = existing_by_name.get(name)
        try:
            if existing is None:
                manager.register_server(config)
                logger.debug(
                    "[project_workspace/mcp] registered project server %r", name
                )
            else:
                config.id = existing.id  # keep stable ID
                manager.update_server(existing.id, config)
                logger.debug(
                    "[project_workspace/mcp] updated server %r with project config",
                    name,
                )
        except Exception as exc:
            logger.warning(
                "[project_workspace/mcp] could not register/update server %r: %s — skipping",
                name,
                exc,
            )


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def apply_mcp_scope(
    scope: str,
    workspace_root: Path | None,
    *,
    _manager: Any = None,
    _project_file: Path | None = None,
) -> None:
    """Inject / disable MCP servers based on the active workspace scope.

    Args:
        scope:          ``"merge"`` | ``"project"`` | ``"global"``
        workspace_root: From ``discover_root()`` / ``config.root``; may be
                        ``None`` when no workspace was found.
        _manager:       Injectable ``MCPManager`` instance for testing.
                        Defaults to ``get_mcp_manager()`` at call time.
        _project_file:  Injectable path to the project ``mcp_servers.json``
                        file for testing.  Defaults to
                        ``workspace_root / ".code_puppy" / "mcp_servers.json"``.

    Never raises — all errors are logged and execution falls through to
    default global behaviour.
    """
    # global scope: noop — keep whatever the manager loaded from global config
    if scope == "global":
        logger.debug("[project_workspace/mcp] scope=global — noop")
        return

    # Resolve manager
    if _manager is None:
        try:
            from code_puppy.mcp_.manager import get_mcp_manager

            manager = get_mcp_manager()
        except Exception as exc:
            logger.warning(
                "[project_workspace/mcp] could not get MCPManager: %s — skipping",
                exc,
            )
            return
    else:
        manager = _manager

    # No workspace root: fall through to global for all remaining scopes
    if workspace_root is None and _project_file is None:
        logger.debug(
            "[project_workspace/mcp] no workspace root — falling through to global"
        )
        return

    # Resolve project file path
    if _project_file is not None:
        project_file = _project_file
    else:
        project_file = workspace_root / ".code_puppy" / "mcp_servers.json"  # type: ignore[operator]

    # Load project servers
    project_servers = _load_mcp_servers_from_file(project_file)

    # project scope with no project servers → fall through to global
    if scope == "project" and not project_servers:
        logger.debug(
            "[project_workspace/mcp] project scope but no mcp_servers.json "
            "— falling through to global"
        )
        return

    # Snapshot currently registered servers (global, pre-injection)
    try:
        existing_configs = manager.registry.list_all()
    except Exception as exc:
        logger.warning(
            "[project_workspace/mcp] could not list registry servers: %s — skipping",
            exc,
        )
        return

    existing_by_name: dict[str, Any] = {c.name: c for c in existing_configs}

    # Unknown scope: warn + fall back to merge behaviour
    if scope not in ("merge", "project"):
        logger.warning(
            "[project_workspace/mcp] unknown scope %r — falling back to merge",
            scope,
        )

    # Inject project servers (merge + project + unknown fallback)
    _inject_servers(project_servers, manager, existing_by_name)

    # project scope: disable global servers not overridden by project
    if scope == "project":
        project_names = set(project_servers.keys())
        for existing_config in existing_configs:
            if existing_config.name not in project_names:
                try:
                    managed = manager.get_server(existing_config.id)
                    if managed is not None:
                        managed.disable()
                        logger.debug(
                            "[project_workspace/mcp] disabled global server %r",
                            existing_config.name,
                        )
                except Exception as exc:
                    logger.warning(
                        "[project_workspace/mcp] could not disable server %r: %s",
                        existing_config.name,
                        exc,
                    )


# ---------------------------------------------------------------------------
# Registration
# ---------------------------------------------------------------------------


def register() -> None:
    """Wire the MCP surface into a second ``startup`` callback.

    Called at plugin import time from ``register_callbacks.py``.  The
    workspace config is read *inside* the callback body (at call time) so
    that the first ``startup`` callback (which populates ``_active_config``)
    has already fired before this one runs.
    """
    from code_puppy.callbacks import register_callback

    def _mcp_startup() -> None:
        try:
            from code_puppy.plugins.project_workspace.register_callbacks import (
                get_active_config,
            )

            config = get_active_config()
            scope = config.surfaces.get("mcp", "merge")
            workspace_root = config.root

            logger.debug(
                "[project_workspace/mcp] startup fired — scope=%s root=%s",
                scope,
                workspace_root,
            )

            apply_mcp_scope(scope, workspace_root)

        except Exception as exc:
            logger.warning("[project_workspace/mcp] surface error: %s — skipping", exc)

    register_callback("startup", _mcp_startup)
